# Get PhoneBook title
GET http://localhost:3001

###
# Get info
GET http://localhost:3001/info

###
# Get all the persons in the phonebook
GET http://localhost:3001/api/persons

###
# Get single person 
GET http://localhost:3001/api/persons/67e333297390baa0c4574d7a

###
# Remove single person
DELETE http://localhost:3001/api/persons/67e47b1a258bc1ceae1a7ee7

###
# Adding a new person to the phonebook
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alessandro Caula",
    "number": "+39 319 222 0692"
}