###
# POST a new user
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

### 
# GET all the users
GET http://localhost:3001/api/users/

###
# Create a new note from the root user
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "User id of the note creator is at the start sent along the request",
    "important": true,
    "userId": "6806b600812d0eea7f6a1e71"
}