# Get home page, root directory
GET http://localhost:3003

###
# Get list with all the stored blogs
GET http://localhost:3003/api/blogs

###
# Post a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog 3",
  "author": "Author 3",
  "url": "url 3",
  "likes": 3
}

###
# Deleting a blog
DELETE http://localhost:3003/api/blogs/68050f1e375be96ef95d1c28

###
# Updating a blog
PUT http://localhost:3003/api/blogs/67f17c523398011aecf08a36
Content-Type: application/json

{
  "likes": 42
}