# Get home page, root directory
GET http://localhost:3001

###
# Get list with all the stored blogs
GET http://localhost:3001/api/blogs

###
# Post a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Blog 7",
    "author": "Author 7",
    "url": "url 7",
    "likes": 10
}

###
# Post a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Blog 3",
    "author": "Author 3",
    "url": "url 3",
    "likes": 8
}